### ISSUE TITLE
DEPRECATION: Addon files

### ISSUE THREAD

**Issue by haldiggs** [clairton/ember-maskmoney#10]
I know this project is possibly not updated regularly but I cannot do a pull from my office.

Ember 2.12 chokes on this issue
DEPRECATION: Addon files were detected in `/node_modules/ember-maskmoney/addon`, but no JavaScript preprocessors were found for `ember-maskmoney`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-maskmoney`'s `package.json`.

which is fixed by moving ember-cli-babel location in the package.json

  "dependencies": {
    "ember-cli-babel": "^5.1.5"
  },
  "description": "An ember-cli addon for creating money masks on text fields.",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.15",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-try": "0.2.9"
  },

**Comment by clairton** [comment]
Thanks @haldiggs 
Version 0.3.5 is released with this fix.

**Comment by haldiggs** [comment]
you rock
