### ISSUE TITLE
Display does not update when component parameters change

### ISSUE THREAD

**Issue by tythewebguy** [clairton/ember-maskmoney#17]
If I change the value of `suffix` or `prefix` parameters, the `input-money` component does not update to reflect those changes. 

This is fixed by adding an observer that watches the `options` CP and calls `.maskMoney('mask')` to update the display whenever the parameter values change.

**Comment by clairton** [comment]
Hi @tythewebguy, thank's for your PR.
I released the version 0.4.6.
If it work's, close the issue please =)
