### ISSUE TITLE
Can't type in input with certain settings

### ISSUE THREAD

**Issue by Jordan4jc** [clairton/ember-maskmoney#5]
I'm trying to make an input that is masked like `'$0` basically with a `$` prefix and no decimal, starting with a 0

`{{mask-money prefix="$" precision="0" number=donationAmount class="donate-amt-input" }}`

When I remove the `precision` setting I can type but I don't want any decimals, any thoughts?

**Comment by clairton** [comment]
Sorry for the delay, I did not see your question.
The problem was already solved?

**Comment by Jordan4jc** [comment]
Oh yeah sorry I think I ended up grabbing a jquery library and building it out myself in a component since I'll have a lot of other masked inputs floating around my app
